### PR TITLE
Added more formats (TEX, ASCII, ORG, PDF ...)

### PR DESCRIPTION
**Pull request by thecsw**
Hey! I added more formats to make it look more professional and distribute everywhere. Please note that I changed some structure. I swapped 2nd and 3rd paragraphs. It's more logical that way.

### CODE REVIEW

**Comment by thecsw** [comment]
Also, I added `.gitignore` for latex temp files.

**Comment by thecsw** [comment]
That's a no problem! We just need to swap 2nd and 3rd paragraph. About adding versions for each language? We can make it to stay in English or other users can contribute!

**Comment by me-shaon** [comment]
I'm not talking about the current changes you've made (swapping two paragraphs), I'm pointing to any future changes. If it's not updated in each of the formats, then the license won't be consistent overall, right? I want to keep it minimal. I guess, if anyone wants, they can convert the main license to any format they want. This repo will provide only the License itself. I think it's better this way. 
Thanks for your hard work and contribution though. 😃

**Comment by thecsw** [comment]
Alright, understood. However, I still think it's important to swap the paragraphs! Thanks!

**Comment by DinoLeung** [comment]
Maybe it's a good idea to make the license more general by not limiting it to 'code', like creative commons license. But having versions of it specify for different formats might be a bit difficult to manage.

**Comment by me-shaon** [comment]
@thecsw That's a valid point. I'm creating an issue. Would you like to contribute?

**Pull request closed without merging**
