### PR TITLE
Fix German translation

### PR DESCRIPTION
**Pull request by Kijewski**
A "public license" is a "Veröffentlichsungslizenz" (license to publish, instead of a license that is public).

Er/sie (he/she) is written in lower case if it is not the person who you are directly talking to.

An option is a "Möglichkeit". A "Option" is a choice you take, a "Möglichkeit" is forced upon you by a someone else, the fates, whatever.

"Im Falle" is also used for options you have no say in.

"Sowohl" means the particular cases must not all apply, but the license wants none of the cases to apply.

Greetings and good-byes are punctuated with an exclamation point.

### CODE REVIEW

**Comment by me-shaon** [comment]
@cpyix @thecsw Can any of you please review this PR? I don't know the German language.

**Comment by cpyix** [comment]
@me-shaon  seems fine from my side.

**Comment by thecsw** [comment]
@me-shaon lgtm

**Comment by me-shaon** [comment]
Thanks a lot, @cpyix , @thecsw. 🙏

**Comment by Kijewski** [comment]
Thank you!

**Pull request merged**
