### PR TITLE
Add wu chinese translation

### PR DESCRIPTION
**Pull request by 0xDing**

### CODE REVIEW

**Comment by thecsw** [comment]
Hey! Can you move the `README` entry a big higher so it would be after the `Traditional Chinese`? Sort of group them.

**Comment by DinoLeung** [comment]
I think we should rename them e.g. `Chinese - Traditional` so all chinese dialects group together

**Comment by borisding1994** [comment]
@DinoLeung that's a wood idea. I've already fixed it.

**Comment by DinoLeung** [comment]
I think it looks better like this. easier on the eyes
```
[Chinese Cantonese - 中文（廣東話）](translations/LICENSE_zh-HK)
[Chinese Simplified - 中文（简体）](translations/LICENSE_zh-CN)
[Chinese Traditional - 中文（正體）](translations/LICENSE_zh-TW)
[Chinese Wu - 中文（吴语）](translations/LICENSE_zh-wuu)
```

**Comment by DinoLeung** [comment]
also u might want to check out #40 
we are trying to swap the first 2 paragraphs

**Comment by me-shaon** [comment]
@borisding1994 as @DinoLeung pointed out, please make your PR consistent with the #40

**Comment by me-shaon** [comment]
Also, please resolve the conflicts.

**Comment by FrankHB** [comment]
@borisding1994 Is it better to use `清爽` than `清楚`?

@DinoLeung BTW, technically, Extended language subtags is different to Script subtag according to [RFC 5646](https://tools.ietf.org/html/rfc5646). The precise language tag of Traditional Chinese is zh-Hant, not necessarily zh-TW (usually orthographically implying zh-cmn-Hant-TW, namely `Traditional Chinese (Taiwanese Mandarin)` or `正體中文（臺灣華語）`).

**Comment by DinoLeung** [comment]
@FrankHB well noted

**Comment by me-shaon** [comment]
@borisding1994 Could please resolve the conflict so that I can merge the PR?

**Pull request closed without merging**
