### PR TITLE
Basic formatting. Indents.

### PR DESCRIPTION
**Pull request by thecsw**
This would sound like nitpicking but I think it's very important to keep the same number of character per line. Some of the translations' lines were too far off to the right, I just re-indented them to match the original license formatting.

### CODE REVIEW

**Comment by thecsw** [comment]
I don't know Chinese/Mandarin, so I don't how to properly indent it.

**Comment by DinoLeung** [comment]
@thecsw can you elaborate the rules of indentation? e.g. number of character in a line. I can help with chinese formatting

**Comment by me-shaon** [comment]
@DinoLeung I think, there is no convention. Just indent it in a way so that it looks properly aligned.

**Comment by DinoLeung** [comment]
@me-shaon no worries, will submit a PR when I'm done

**Pull request merged**
